### ISSUE TITLE
java.lang.NoClassDefFoundError when using `cfnCreateChangeSet`

### ISSUE THREAD

**Issue by sirkaiserkai** [jenkinsci/pipeline-aws-plugin#121]
### Description
Running the cfnCreateChangeSet causes the exception `java.lang.NoClassDefFoundError`.

**Expected behavior:** 
We were previously using the plugin version `1.26` which worked correctly. 

**Actual behavior:** [What actually happened]
```
java.lang.NoClassDefFoundError: Could not initialize class java.time.zone.ZoneRulesProvider
	at java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.time.ZoneId.of(ZoneId.java:411)
	at java.time.ZoneId.of(ZoneId.java:359)
	at java.time.ZoneId.of(ZoneId.java:315)
	at java.util.TimeZone.toZoneId(TimeZone.java:556)
	at java.time.ZoneId.systemDefault(ZoneId.java:274)
	at java.time.Clock.systemDefaultZone(Clock.java:178)
	at java.time.OffsetDateTime.now(OffsetDateTime.java:212)
	at de.taimos.pipeline.aws.cloudformation.utils.TimeOutRetryStrategy.<init>(TimeOutRetryStrategy.java:15)
	at de.taimos.pipeline.aws.cloudformation.EventPrinter.pollingStrategy(EventPrinter.java:110)
	at de.taimos.pipeline.aws.cloudformation.EventPrinter.waitAndPrintChangeSetEvents(EventPrinter.java:69)
	at de.taimos.pipeline.aws.cloudformation.CloudFormationStack.createChangeSet(CloudFormationStack.java:183)
	at de.taimos.pipeline.aws.cloudformation.CFNCreateChangeSetStep$Execution.whenStackExists(CFNCreateChangeSetStep.java:100)
	at de.taimos.pipeline.aws.cloudformation.CFNCreateChangeSetStep$Execution.whenStackExists(CFNCreateChangeSetStep.java:84)
	at de.taimos.pipeline.aws.cloudformation.AbstractCFNCreateStep$Execution.run(AbstractCFNCreateStep.java:127)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### Environment

**Jenkins-Version:** 2.121.2

**Plugin-Version:**  Version 1.29

**Master/Slave Setup:** Master only.

Thank you!

**Comment by hoegertn** [comment]
Which Java version are you using?

**Comment by sirkaiserkai** [comment]
Java

**Comment by sirkaiserkai** [comment]
We figured it out. We were using OpenJDK doesn't appear to have the class `java.time.zone.ZoneRulesProvider`. We switched over to Oracle's Java SDK and it's working.

**Comment by hoegertn** [comment]
I reopen this issue, as OpenJDK has to be supported by this plugin.
