### ISSUE TITLE
cfnUpdate fails when an updated template removes a parameter

### ISSUE THREAD

**Issue by chizou** [jenkinsci/pipeline-aws-plugin#133]
### Description

Once a stack has been deployed with a template and a parameter is removed, cfnUpdate seems to attempt to pass the parameter that already exists in the stack, thereby causing the update-stack API call to fail.

### Steps to Reproduce

1. Deploy a working stack with parameters
2. Remove a parameter from the stack
3. Re-deploy that stack

**Expected behavior:** 
Stack gets deployed with the missing parameter removed

**Actual behavior:** 
Update fails with the following:
```
com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: Parameters: [CPU] do not exist in the template (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 494a7969-c762-11e8-a70a-411e019a3ec6)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1658)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1322)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.doInvoke(AmazonCloudFormationClient.java:2931)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:2900)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:2889)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.executeUpdateStack(AmazonCloudFormationClient.java:2580)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.updateStack(AmazonCloudFormationClient.java:2552)
	at de.taimos.pipeline.aws.cloudformation.CloudFormationStack.update(CloudFormationStack.java:144)
	at de.taimos.pipeline.aws.cloudformation.CFNUpdateStep$Execution.whenStackExists(CFNUpdateStep.java:103)
	at de.taimos.pipeline.aws.cloudformation.CFNUpdateStep$Execution.whenStackExists(CFNUpdateStep.java:88)
	at de.taimos.pipeline.aws.cloudformation.AbstractCFNCreateStep$Execution.run(AbstractCFNCreateStep.java:127)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

### Environment

**Jenkins-Version:** 2.138

**Java-Version:** jdk-1.8

**Plugin-Version:** 1.32

**Master/Slave Setup:** [Do you run in a master/slave setup?]

**Comment by chizou** [comment]
Apologies, this was a mistake on my part.
