### ISSUE TITLE
s3copy doesn't copy folders

### ISSUE THREAD

**Issue by o0st** [jenkinsci/pipeline-aws-plugin#160]
### Description

`s3copy` doesn't copy folders, throws 404 instead

### Steps to Reproduce

1. Pipeline:
```
pipeline {
    agent {
        ...
    }

    options {
        withAWS(credentials: "some-account")
    }

    stages {
        stage('s3copy dir test') {
            steps {
                script {
                    s3Copy(fromBucket: "some-bucket", 
                            fromPath: "foo-bar/",
                            toBucket: "some-bucket",
                            toPath: "foo-bar2/")
                    }
            }
        }
    }
}
```
2. Run pipeline

**Expected behavior:**
Copies folder and all nested files.
```
Copying s3://some-bucket/foo-bar to s3://some-bucket/foo-bar2

Copy complete
```

**Actual behavior:**
Exception being thrown and copy/sync never occurs.
```
Copying s3://some-bucket/foo-bar to s3://some-bucket/foo-bar2

com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: A00F4C91064D6806; S3 Extended Request ID: 6GdVYHExff+URzOnD8/CH3TPd8JEidoa0L5C+lB7bVBug1PKMpg93PQOKLNqWw0lTDO8e7Bo0E0=), S3 Extended Request ID: 6GdVYHExff+URzOnD8/CH3TPd8JEidoa0L5C+lB7bVBug1PKMpg93PQOKLNqWw0lTDO8e7Bo0E0=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1310)
	at com.amazonaws.services.s3.transfer.TransferManager.copy(TransferManager.java:1977)
	at com.amazonaws.services.s3.transfer.TransferManager.copy(TransferManager.java:1910)
	at com.amazonaws.services.s3.transfer.TransferManager.copy(TransferManager.java:1862)
	at de.taimos.pipeline.aws.S3CopyStep$Execution.run(S3CopyStep.java:251)
	at de.taimos.pipeline.aws.S3CopyStep$Execution.run(S3CopyStep.java:175)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment

**Jenkins-Version:** 
`2.150.2`

**Java-Version:**
`1.8.0_181`

**Plugin-Version:**
`1.36`

**Master/Slave Setup:**
Tested on master

**Comment by ofasterling** [comment]
Hi there, I just noticed that you posted this. It's possible that you are having a similar issue as in https://github.com/jenkinsci/pipeline-aws-plugin/issues/159. You may want to check the last comment where we found a solution.

**Comment by o0st** [comment]
@ofasterling thanks, but It's not the same.
In this case the method fails to copy whole folder but works fine for a single file.

**Comment by abhishek-anand13** [comment]
The AWS SDK copy supports only one object to be copied at a time. 

> A "folder" is not an object in S3, that is why you can not get it by key, but the folder path is actually a prefix for all the keys of the objects contained by the folder. 

So in order to copy a complete folder, the copy algorithm has to be repeated for the number of objects in the folder. This implementation is not in the plugin since this is a very unusual case.
