### ISSUE TITLE
Some of the CannedAccessControlList values throw error

### ISSUE THREAD

**Issue by jmunozco** [jenkinsci/pipeline-aws-plugin#183]
### Description

From Jenkins instance, using `withAws` and `s3Upload` command some of the CannedAccessControlList values throws error and some not.

### Steps to Reproduce

1. Configure credentials in Jenkins like this 
2. Include the following code:

```
        withAWS(region: 'us-west-2', credentials: 's3cred') {
            //s3Upload(bucket: 'jesusgc1', path: "folder1/", path: "build/$version/bundles", workingDir: 'web/bundles', includePathPattern: '**/*', acl: 'PublicRead')
            s3Upload(bucket: 'jesusgc1', path: "folder1", workingDir: 'web/vendor', includePathPattern: 'system*', acl: 'AwsExecRead')
            //s3Upload(bucket: 'jesusgc1', path: "build/$version/bundles", workingDir: 'web/bundles', includePathPattern: '**/*', acl: 'PublicRead')
            awsIdentity()
            s3Download(file: 'africa.jpg', bucket: 'jesusgc1', path: '/')
        }
```

3. Depending on `acl` parameter it works or not. I tried for all of the values and here are the results.
It works: `Private`, `LogDeliveryWrite`, `BucketOwnerRead`, `BucketOwnerFullControl`, `AwsExecRead`
And it does not work for: `PublicRead`, `PublicReadWrite`, `AuthenticatedRead`

When it throws error, it is this:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: <code-removed>; S3 Extended Request ID: <code-removed>), S3 Extended Request ID: <code-removed>
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4920)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4866)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:389)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:5800)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1789)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1749)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior:** To work for all of them

**Actual behavior:** `acl` parameter throws error on some cases

### Environment

**Jenkins-Version:** 2.176.1

**Java-Version:** openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-b04) OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

**Plugin-Version:** 1.37

**Master/Slave Setup:** only master

**Comment by xzhorikx** [comment]
I've just encountered same issue when trying to send `s3Upload` request with `acl:'PublicRead'` param.

As I found out that appeared due to insufficient policies of my S3 account. I needed to put `"s3:PutObjectAcl"` within `Statement.Action`. Now my user's policy looks following way:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::my_resource*"
            ]
        }
    ]
}
```

**Comment by kamcknig** [comment]
>             "Action": [

Anything else you can think of that would cause this? I have the PutObjectAcl action but it's still failing for me

**Comment by kamcknig** [comment]
> I've just encountered same issue when trying to send `s3Upload` request with `acl:'PublicRead'` param.
> 
> As I found out that appeared due to insufficient policies of my S3 account. I needed to put `"s3:PutObjectAcl"` within `Statement.Action`. Now my user's policy looks following way:
> 
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "s3:PutObject",
>                 "s3:GetObject",
>                 "s3:DeleteObject",
>                 "s3:PutObjectAcl"
>             ],
>             "Resource": [
>                 "arn:aws:s3:::my_resource*"
>             ]
>         }
>     ]
> }
> ```

Anything else you can think of that would cause this? I have the PutObjectAcl action but it's still failing for me

**Comment by hoegertn** [comment]
Did you try looking into CloudTrail to see which actions fail? But this might be a DataAPI call so you would have to activate this first.

**Comment by kamcknig** [comment]
I forgot I had posted here! The actual problem was that when I set up the bucket I had chosen the policy that disallows future public items from being added. This setting when creating a bucket prevented future public items.

![2020-07-31 10_07_54-Window](https://user-images.githubusercontent.com/705490/89042941-c3bdef00-d315-11ea-8424-b73081832785.png)
