### ISSUE TITLE
UnknownHostException during S3Upload

### ISSUE THREAD

**Issue by dhet** [jenkinsci/pipeline-aws-plugin#192]
### Description

I'm trying to upload a file to S3 using s3Upload but I'm receiving an UnknownHostException. Note that the bucket is in fact there and i can upload files to it from CLI via 
```
aws s3 cp testfile.txt s3://bucketxxx
``` 
as usual. What is striking is that the UnknownHostException includes the region in the URL which I'm not sure is the correct behavior:
```
java.net.UnknownHostException: bucketxxx.s3.eu-central-1.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy18.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1285)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
```
I have also verified that I can connect to AWS from my Jenkins instance: awsIdentity() works. The bucket is public

### Steps to Reproduce

I'm using this snipped to upload the file:
```
withAWS(role: "xxx", roleAccount: "xxx", region: "eu-central-1", credentials: "aws") {
  s3Upload(file: "testfile.txt", bucket: "bucketxxx")
}
```

**Expected behavior:** File is uploaded

**Actual behavior:** The following error occurs 
`java.net.UnknownHostException: bucketxxx.s3.eu-central-1.amazonaws.com`

### Environment

**Jenkins-Version:** 2.138.4

**Java-Version:** ?

**Plugin-Version:** 1.38

**Master/Slave Setup:** yes

**Comment by ajinkyakadam** [comment]
@dhet I had the same issue but for downloads. Opened #198

**Comment by dhet** [comment]
Found the problem: the corporate DNS couldn't resolve the S3 host (as the error message suggests). Using a proxy with internet access solved the issue. It might also be worth mentioning that this plugin honors the `http_proxy`/`https_proxy`/`no_proxy` environment variables.
