### ISSUE TITLE
Wrong pre-condition check in S3Upload step

### ISSUE THREAD

**Issue by sbienkow** [jenkinsci/pipeline-aws-plugin#196]
### Description

https://github.com/jenkinsci/pipeline-aws-plugin/pull/168 added the ability to pass text to upload as files to S3 bucket. Unfortunately pre-conditions weren't changed to allow for using it: https://github.com/jenkinsci/pipeline-aws-plugin/blob/master/src/main/java/de/taimos/pipeline/aws/S3UploadStep.java#L304

### Steps to Reproduce

1. Try uploading any text to S3, i.e. from README:
```
s3Upload(path: 'file.txt', bucket: 'my-bucket', text: 'Some Text Content')
s3Upload(path: 'path/to/targetFolder/file.txt', bucket: 'my-bucket', text: 'Some Text Content')
```

**Expected behavior:** Text is uploaded as file

**Actual behavior:** Illegal argument exception is being thrown
```
java.lang.IllegalArgumentException: File or IncludePathPattern must not be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
	at de.taimos.pipeline.aws.S3UploadStep$Execution.run(S3UploadStep.java:293)
	at de.taimos.pipeline.aws.S3UploadStep$Execution.run(S3UploadStep.java:252)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Environment

**Plugin-Version:** 1.37, but master is also affected

**Comment by nom3ad** [comment]
@helver can you please have a look into this when you get time.
I could also reproduced this in v1.42.   Finally ended up  to create file and upload it.
```
Error when executing success post condition:
java.lang.IllegalArgumentException: File or IncludePathPattern must not be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:88)
	at de.taimos.pipeline.aws.S3UploadStep$Execution.run(S3UploadStep.java:349)
	at de.taimos.pipeline.aws.S3UploadStep$Execution.run(S3UploadStep.java:295)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by helver** [comment]
@nom3ad , @webark - Sorry for the slow response on this...

**Comment by nraval1729** [comment]
I faced this earlier today as well. Is there anything I can do to help out @helver? I'd be happy to provide a fix in case you are all low on bandwidth.

**Comment by helver** [comment]
Thanks for the offer @nraval1729 !  I still don't know what that PR failed, though....

**Comment by helver** [comment]
Looks like the PR is ready... just needs an approval.
