### ISSUE TITLE
s3Delete function stopped working suddenly !

### ISSUE THREAD

**Issue by peimansh** [jenkinsci/pipeline-aws-plugin#203]
### Description

We are using this plugin for our website deployment in Jenkins. Then we suddenly (not sure if there was a plugin/jenkins update in our company Jenkins instance) began returning error for a function where we try to delete a folder object in s3 bucket.
It's a cache folder for our application where it needs to be cleared before the deploy continues.
The role for Jenkins has been assumed using withAWS and there has been no change regarding that.
The command looks like this: 
```
s3Delete(
            bucket: "$bucket-name",
            path: "cpresources/norev/",
        )
```
And it is returning this error complaining on a dependency which we already have in place.

```
s3Delete
11:08:02  Deleting s3://bucket-name/cpresources/norev/

java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:565)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:82)
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:228)
Caused: org.xml.sax.SAXException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:230)
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:191)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:120)
Caused: com.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:123)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$ListObjectsUnmarshaller.unmarshall(Unmarshallers.java:109)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$ListObjectsUnmarshaller.unmarshall(Unmarshallers.java:99)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:31)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1627)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1336)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4861)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:880)
	at de.taimos.pipeline.aws.S3DeleteStep$Execution$1.searchObjectsRecursively(S3DeleteStep.java:188)
	at de.taimos.pipeline.aws.S3DeleteStep$Execution$1.deleteFolder(S3DeleteStep.java:148)
	at de.taimos.pipeline.aws.S3DeleteStep$Execution$1.run(S3DeleteStep.java:129)
```

**Expected behavior:** It was working fine but then it began returning this error.
The output before this error showed up was like this: 

```
s3Delete
16:26:08  Deleting s3://bucket-name/cpresources/norev/

16:26:15  Delete complete
```

### Environment

**Jenkins-Version:** [2.176.2]

**Java-Version:** [8u212 - openjdk 1.8]

**Plugin-Version:** [1.38]

**Comment by peimansh** [comment]
The problem is solved after restarting the Jenkins instance. Seems like the instance was not restarted after installing the new version of the plugin.
