### ISSUE TITLE
java.lang.NoClassDefFoundError while running build on TFS build server

### ISSUE THREAD

**Issue by hardyvala** [jenkinsci/pipeline-aws-plugin#206]
**Description**

When my build server executing received the following errors.

Exception in thread "vert.x-eventloop-thread-2" java.lang.NoClassDefFoundError: Could not initialize class java.time.zone.ZoneRulesProvider
	at java.base/java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.base/java.time.ZoneId.of(ZoneId.java:408)
	at java.base/java.time.ZoneId.of(ZoneId.java:356)
	at java.base/java.time.ZoneId.of(ZoneId.java:312)
	at java.base/java.util.TimeZone.toZoneId0(TimeZone.java:573)
	at java.base/java.util.TimeZone.toZoneId(TimeZone.java:550)
	at java.base/java.util.TimeZone.toZoneId0(TimeZone.java:562)
	at java.base/java.util.TimeZone.toZoneId(TimeZone.java:550)
	at java.base/java.time.ZoneId.systemDefault(ZoneId.java:272)
	at java.logging/java.util.logging.SimpleFormatter.format(SimpleFormatter.java:158)
	at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:199)
	at java.logging/java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:95)
	at java.logging/java.util.logging.Logger.log(Logger.java:979)
	at io.netty.util.internal.logging.JdkLogger.log(JdkLogger.java:606)
	at io.netty.util.internal.logging.JdkLogger.warn(JdkLogger.java:482)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:908)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

Java version is --  11.0.4
Vert.x version is -- 3.8.0

**Comment by hoegertn** [comment]
Is this still an issue?

**Comment by hardyvala** [comment]
No after updating the version this issue has been resolved.
