### ISSUE TITLE
cfnExecuteChangeSet() doesn't update a stack when only Outputs change

### ISSUE THREAD

**Issue by nielslaukens** [jenkinsci/pipeline-aws-plugin#210]
### Description

It seems that `cfnExecuteChangeSet` doesn't execute a ChangeSet when the only thing that changes are Outputs of a stack.

### Steps to Reproduce

1. Create a CloudFormation stack using whatever method you want. Make sure it has an Output() specified
2. Modify the CloudFormation template to (also) Export the Output mentioned in step 1.
3. prepare the ChangeSet for the modification in step 2
4. Use `cfnExecuteChangeSet()` to execute the ChangeSet prepared in step 3.

**Expected behavior:** The stack is updated and the Output has its ExportName added

**Actual behavior:** The ChangeSet is deleted without being executed:

```
[Pipeline] cfnExecuteChangeSet
Executing CloudFormation change set arn:aws:cloudformation:eu-west-1:000000000000:changeSet/xxxx/0000-00-00-0-00 
Deleting empty change set arn:aws:cloudformation:eu-west-1:000000000000:changeSet/xxxx/0000-00-00-0-00  for stack xxxx 
Execute change set complete
```

I believe the corresponding code is https://github.com/jenkinsci/pipeline-aws-plugin/blob/211faf6b3157741212de1e69060be09e8dcf155d/src/main/java/de/taimos/pipeline/aws/cloudformation/CloudFormationStack.java#L224-L234

### Environment

**Jenkins-Version:** 2.176.1

**Java-Version:** oracle-java8-jdk 8u144-1

**Plugin-Version:** 1.37

**Master/Slave Setup:** yes, dynamic slaves

**Comment by wimsymons** [comment]
Hmmm not automatically closed. It's fixed now.

**Comment by akuntsch** [comment]
This fix seems to break something in my case where the change set is actually empty (no changes and no changed stack outputs).

Console output with previous plugin version (no error, pipeline is green):
```
[Pipeline] cfnCreateChangeSet
17:20:24  Found 1 stacks in result 
17:20:24  Found stackName=mystack stackId=mystackid status=UPDATE_COMPLETE statusReason=null in result 
17:20:24  Found 1 stacks in result 
17:20:24  Found stackName=mystack stackId=mystackid status=UPDATE_COMPLETE statusReason=null in result 
17:20:24  Creating CloudFormation change set mystack for existing stack mystack 
17:20:24  Setting up a polling strategy to poll every PT5S for a maximum of PT5M
17:20:24  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
17:20:24  | Stack: mystack                                                                                                                                                                             |
17:20:24  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
17:20:30  Found changeSet=mystack status=FAILED statusReason=The submitted information didn't contain changes. Submit different information to create a change set. 
17:20:30  Created empty change set mystack for stack mystack 
[Pipeline] cfnExecuteChangeSet
17:20:30  Executing CloudFormation change set mystack 
17:20:30  Deleting empty change set mystack for stack mystack 
17:20:30  Execute change set complete
```

Console output with most recent plugin version where this fix is included (error, pipeline is red):
```
[Pipeline] cfnCreateChangeSet
11:33:46  Found 1 stacks in result 
11:33:46  Found stackName=mystack stackId=mystackid status=UPDATE_COMPLETE statusReason=null in result 
11:33:47  Found 1 stacks in result 
11:33:47  Found stackName=mystack stackId=mystackid status=UPDATE_COMPLETE statusReason=null in result 
11:33:47  Creating CloudFormation change set mystack for existing stack mystack 
11:33:47  Setting up a polling strategy to poll every PT5S for a maximum of PT5M
11:33:47  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
11:33:47  | Stack: mystack                                                                                                                                                                             |
11:33:47  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
11:33:52  Found changeSet=mystack status=FAILED statusReason=The submitted information didn't contain changes. Submit different information to create a change set. 
11:33:52  Created empty change set mystack for stack mystack 
[Pipeline] cfnExecuteChangeSet
11:33:52  Executing CloudFormation change set mystack 
11:33:53  Found 1 stacks in result 
11:33:53  Found stackName=mystack stackId=mystackid status=UPDATE_COMPLETE statusReason=null in result 
11:33:53  Executing change set mystack for stack mystack 
11:33:53  Found 1 stacks in result 
11:33:53  Found stackName=mystack stackId=mystackid status=UPDATE_COMPLETE statusReason=null in result 
com.amazonaws.services.cloudformation.model.InvalidChangeSetStatusException: ChangeSet [mystack] cannot be executed in its current status of [FAILED] (Service: AmazonCloudFormation; Status Code: 400; Error Code: InvalidChangeSetStatus; Request ID: reqid; Proxy: myproxy)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.doInvoke(AmazonCloudFormationClient.java:3891)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:3858)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:3847)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.executeExecuteChangeSet(AmazonCloudFormationClient.java:2224)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.executeChangeSet(AmazonCloudFormationClient.java:2195)
	at de.taimos.pipeline.aws.cloudformation.CloudFormationStack.executeChangeSet(CloudFormationStack.java:266)
	at de.taimos.pipeline.aws.cloudformation.CFNExecuteChangeSetStep$Execution.run(CFNExecuteChangeSetStep.java:137)
	at de.taimos.pipeline.aws.cloudformation.CFNExecuteChangeSetStep$Execution.run(CFNExecuteChangeSetStep.java:114)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

So maybe the fix isn't as simple as removing the `changeSetHasChanges()` call from the `if` condition.

**Comment by tylersouthwick** [comment]
The previous fixed created a regression for completely empty changesets
