### ISSUE TITLE
Encountered Throttle

### ISSUE THREAD

**Issue by MastersoftGroup** [jenkinsci/pipeline-aws-plugin#245]
[X] 🐞 Bug
[ ] 🚀 Feature
[ ] 🛠 Task
[ ] 📄 Documentation

### Description

In Jenkinsfile pipeline, when running 10 `cfnUpdate` in parallel stages, encountered below  'Rate exceeded' Throttling AmazonCloudFormationException for 3-4 out of 10 `cfnUpdate`. When I ran with 7 `cfnUpdate` in parallel stages, it was successful. Is this a known issue?

Note: if it is because of the rate limiting problem that is mentioned under `cfnUpdate` section in `README.md`, I got the same 'Rate exceeded' Throttling exception with `pollInterval:0` which is not printing at all or with default `pollInterval`, which is 1ms.

```
com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: Rate exceeded (Service: AmazonCloudFormation; Status Code: 400; Error Code: Throttling; Request ID: d0a7a717-af9f-4f54-a356-a84614abd16c)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
		at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.doInvoke(AmazonCloudFormationClient.java:3219)
		at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:3186)
		at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:3175)
		at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.executeDescribeStacks(AmazonCloudFormationClient.java:1639)
		at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.describeStacks(AmazonCloudFormationClient.java:1610)
		at com.amazonaws.services.cloudformation.waiters.DescribeStacksFunction.apply(DescribeStacksFunction.java:53)
		at com.amazonaws.services.cloudformation.waiters.DescribeStacksFunction.apply(DescribeStacksFunction.java:24)
		at com.amazonaws.waiters.WaiterExecution.getCurrentState(WaiterExecution.java:102)
		at com.amazonaws.waiters.WaiterExecution.pollResource(WaiterExecution.java:74)
		at com.amazonaws.waiters.WaiterImpl.run(WaiterImpl.java:88)
		at com.amazonaws.waiters.WaiterImpl$1.call(WaiterImpl.java:110)
		at com.amazonaws.waiters.WaiterImpl$1.call(WaiterImpl.java:106)
	Caused: java.util.concurrent.ExecutionException
Caused: java.util.concurrent.ExecutionException
	at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:71)
	at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:84)
	at de.taimos.pipeline.aws.cloudformation.EventPrinter.waitAndPrintEvents(EventPrinter.java:161)
	at de.taimos.pipeline.aws.cloudformation.EventPrinter.waitAndPrintStackEvents(EventPrinter.java:109)
	at de.taimos.pipeline.aws.cloudformation.CloudFormationStack.create(CloudFormationStack.java:135)
	at de.taimos.pipeline.aws.cloudformation.CFNUpdateStep$Execution.whenStackMissing(CFNUpdateStep.java:110)
	at de.taimos.pipeline.aws.cloudformation.CFNUpdateStep$Execution.whenStackMissing(CFNUpdateStep.java:88)
	at de.taimos.pipeline.aws.cloudformation.AbstractCFNCreateStep$Execution.run(AbstractCFNCreateStep.java:130)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce

1. Create a Jenkins job with Jenkinsfile: declarative stage with 10 parallel stages - each call `cfnUpdate`. It will call a nested AWS CloudFormation template:, which will create ECS task definition, Target Group, ALB Listener Rule, ECS service nested stacks (ALB Listener already created manually in AWS console).
2. Run the Jenkins job

**Expected behavior:** will create all 10 services successfully, no exception

**Actual behavior:** will encounter 'Rate exceeded' Throttling exception as above

### Environment

**Jenkins-Version:** 2.235.1

**Java-Version:** [put your Java version here]

**Plugin-Version:** 1.41

**Master/Slave Setup:** [Do you run in a master/slave setup?]

**Comment by hoegertn** [comment]
This is part of the rate-limiting of CFN. The pollInterval option should mitigate this.

**Comment by MastersoftGroup** [comment]
Yes, it does not give me this exception with `pollInterval: 5000`. I was still getting this exception with `pollInterval: 3000` and without setting `pollInterval`, which by default is `1000`. But why when I ran with `pollInterval: 0`, it was still throwing this `Rate exceeded` throttling exception?

**Comment by tylersouthwick** [comment]
`pollInterval: 0` essentially tells it not to wait, so you'll be making a lot of calls and it is expected that AWS will throttle that. The default is to poll every second.

If you keep running into the problem, you can request the limit to be raised on the AWS side. It may or may not be increased.
