### ISSUE TITLE
Getting a ERROR: com.amazonaws.AmazonClientException: Unable to complete transfer: Failed to load com.sun.xml.bind.StackHelper

### ISSUE THREAD

**Issue by gdubs** [jenkinsci/pipeline-aws-plugin#299]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Pipeline is running using containerTemplates with 'docker' as one of them. The issue happens intermittently but there's no documentation to show what are the possible causes of it. It happens when uploading a tar file using the following:

```
            try {
                withAWS(role: jenkinsRole) {
                    awsIdentity()
                    echo "uploading ${newChart}"
                    s3Upload(bucket: 'mybucket/folderkey', file: newChart)
                    echo "uploaded"

                }
             }
            catch (e) {
                error e.toString()
            }
```

File I'm uploading is a tar file packaged using helm. There will also be multiple packaged files, so looping can happen to to upload multiple packaged files.

### Reproduction steps

1. Setup a role that jenkins will assume
2. Use declarative pipeline for the script and podTemplate to run the slave agent
3. Package multiple helm charts and upload 
4. Re package again with different file names and try uploading. 
5. Error will happen intermittently between builds

### Expected Results

Uploaded files to bucket

### Actual Results

Error on the first tar file upload attempt

**Comment by DavidSanchezAlvarez** [comment]
We are experiencing the same exact behaviour when running a pipeline that uploads frontend files to S3, in an identical scenario. The problem repits intermittently. Just running the pipeline few minutes after it runs smoothly.

org.codehaus.groovy.runtime.InvokerInvocationException: com.amazonaws.AmazonClientException: Unable to complete transfer: Failed to load com.sun.xml.bind.StackHelper

**Comment by krishna295** [comment]
we are also seeing same issue, anyone has solution?

Caused: com.amazonaws.AmazonClientException: Unable to complete transfer: Failed to load com.sun.xml.bind.StackHelper
18:53:30  	at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.unwrapExecutionException(AbstractTransfer.java:286)
18:53:30  	at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.rethrowExecutionException(AbstractTransfer.java:265)
18:53:30  	at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.waitForCompletion(AbstractTransfer.java:103)
18:53:30  	at de.taimos.pipeline.aws.S3UploadStep$RemoteUploader.invoke(S3UploadStep.java:583)
18:53:30  	at de.taimos.pipeline.aws.S3UploadStep$RemoteUploader.invoke(S3UploadStep.java:481)
18:53:30  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3502)

**Comment by wuillaum** [comment]
We had luck with running Jenkins under Java 8. It looks like this could be Java 11 related?

**Comment by asmild** [comment]
Faced this issue with 1.43 version of plugin (jenkins is running with java11)

**Comment by rkivisto** [comment]
For anyone encountering this issue, it would be helpful if you can confirm that:

* If you are running your controller with Java 11, ensure the build agents are also using Java 11 to launch the `agent.jar`
* Ensure you have https://plugins.jenkins.io/aws-java-sdk-minimal plugin version `1.12.215-339.vdc07efc5320c` or newer installed on your controller

The reason I suggest this, is because the error `Failed to load com.sun.xml.bind.StackHelper` would typically mean we are encountering https://openjdk.org/jeps/320#Java-EE-modules, and this was fixed by PR https://github.com/jenkinsci/aws-java-sdk-plugin/pull/710 (https://issues.jenkins.io/browse/JENKINS-68450) which was first available in https://plugins.jenkins.io/aws-java-sdk-minimal/#releases version `1.12.215-339.vdc07efc5320c`.

This plugin currently only pulls in version:
https://github.com/jenkinsci/pipeline-aws-plugin/blob/693f49f51bda7a8738060eba2e90da8b7033c645/pom.xml#L140

If anyone finds that this solves your issue, please reply or add a 👍

**Comment by rkivisto** [comment]
@asmild since you encountered this issue just 12 days ago, did the above solution help?

**Comment by allamgr** [comment]
@rkivisto we are using:
```
Java Version: 11.0.15
Amazon Web Services SDK :: Minimal Version1.12.246-349.v96b_b_f7eb_a_c3c
```
I'm still getting the error, maybe we can just run `aws s3` command instead of using the plugin.
