### ISSUE TITLE
Support the AWS Credentials plugin

### ISSUE THREAD

**Issue by tekkamanendless** [jenkinsci/pipeline-aws-plugin#45]
The AWS Credentials plugin (https://wiki.jenkins.io/display/JENKINS/CloudBees+AWS+Credentials+Plugin) provides a specific AWS credential type that includes access key ID and secret access key so that we don't have to hack around "username" and "password" in standard password credentials.  The intent of that plugin is that all other AWS plugins should use it.

I currently have to duplicate my AWS users; I have a set that work with this plugin (pipeline-aws-plugin) and a set that work with everything else (using the AWS credentials plugin).

I'd like to add the AWS credentials plugin as a dependency of this one and support _both_ the username/password method (for backward compatibility) as well as the AWS credentials (to be more in line with the AWS design).

Would that be okay with you guys?

**Comment by hoegertn** [comment]
Sounds great, but it should not break the current behavior of the withAWS step.
Especially the assume role should still work as designed.

So supporting it as AccessKey/SecretKey store is great but combining the other credentials features of the AWS cred plugin might be harder and break some stuff.

**Comment by dtd379** [comment]
Using the AWS Credentials plugin breaks the withAWS credentials function:
java.lang.RuntimeException: Cannot find a Username with password credential with the ID <whatever>

Right now, I've got to stuff withAWS into a withCredentials block if I want to store my aws credentials in jenkins.

`withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: '<whatever>', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
    withAWS(role:'<whatever>', roleAccount:"${awsAccountId}",duration:'3600') {
        <code stuffs>
    }
}`

**Comment by ryandavis84** [comment]
Created a PR for this

**Comment by surajdevops18** [comment]
Hi ,
I have added my AWS credentials in Jenkins using AWS credentials plugin and tried to use in below Jenkins file.

pipeline {
	agent any
	stages {
		stage('Deploy VPC') {
			steps {
				withAWS(credentials: 'aws-credentials', region: 'us-west-2'){
					sh 'aws iam get-user'
				}
			

			}
		}
	}	
		

		
}

getting below errors 
java.lang.RuntimeException: Cannot find a Username with password credential with the ID aws-credentials
	at de.taimos.pipeline.aws.WithAWSStep$Execution.withCredentials(WithAWSStep.java:360)
	at de.taimos.pipeline.aws.WithAWSStep$Execution.start(WithAWSStep.java:290)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
