### ISSUE TITLE
Can you support aws region "cn-north-1"? 

### ISSUE THREAD

**Issue by qantnull** [jenkinsci/pipeline-aws-plugin#80]
When I choose china aws in my config file, I got a problem "
The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 8BC96FABC523A70E; S3 Extended Request ID: rWbKZrKu5W1QHlAQkZMQN8H7XQ2M5R61YJu1KYLRsUohN48/jKvPMKkLhcE5cDST9neJiV1ABEQ=)".
<I'm sure that my IAM permissions are correct.>

**Comment by hoegertn** [comment]
Can you post more information about your pipeline and your setup? Unfortunately, I cannot test this as I do not have access to a China account.

**Comment by qantnull** [comment]
I use profile information from ~/.aws/config and I have two profile China and Japan. 
When I use China profile like this 
`withAWS(profile:'China') {
    s3Upload(file:'.', bucket:'circleci-code', path:'test/txgh-test')
}` 
I got what I first post. 
About detail errors in Java: 

> com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: 8BC96FABC523A70E; S3 Extended Request ID: rWbKZrKu5W1QHlAQkZMQN8H7XQ2M5R61YJu1KYLRsUohN48/jKvPMKkLhcE5cDST9neJiV1ABEQ=), S3 Extended Request ID: rWbKZrKu5W1QHlAQkZMQN8H7XQ2M5R61YJu1KYLRsUohN48/jKvPMKkLhcE5cDST9neJiV1ABEQ=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4325)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4272)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1749)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:133)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:125)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE  

If I use Japan profile, everything is ok. 

I think it related to the different endpoints of aws. China has the endpoint "amazonaws.com.cn".

**Comment by riznob** [comment]
@hoegertn Was this issue closed because China regions will not be supported by this plugin?

**Comment by hoegertn** [comment]
If anybody wants to help build this I would welcome it. I cannot test it as I do not have China access.

**Comment by moises-perez-tfs** [comment]
FYI. The issues reported above are resolved by specifying the region.
