### ISSUE TITLE
MissingPropertyException using groovy variables for credential id

### ISSUE THREAD

**Issue by njdart** [jenkinsci/pipeline-aws-plugin#91]
I'm trying to use a variable to store my credentials ID in, and i'm getting `groovy.lang.MissingPropertyException` exceptions; 

```groovy
// An AWS type credential. This is used to manipulate AWS through terraform and the AWS CLI
def SECRET_AWS_CREDENTIALS_ID = "aws-credentials"

...

withAWS(region:'us-east-1', credentials: SECRET_AWS_CREDENTIALS_ID) {
    s3Upload(
        bucket: "xxxxxxx",
        path: "/",
        includePathPattern: '*'
    )
}
```

```
Also:   groovy.lang.MissingPropertyException: No such property: SECRET_AWS_CREDENTIALS_ID for class: WorkflowScript
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
        at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:290)
        at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
        at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:326)
        at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:288)
        at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:292)
        at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
        at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
        at WorkflowScript.archiveArtifactsS3(WorkflowScript:246)
        at WorkflowScript.run(WorkflowScript:76)
```

**Comment by njdart** [comment]
Never mind, It turned out to be a groovy issue. Removing the `def` from my variable definition fixed the problem;

```diff
2c2
< def SECRET_AWS_CREDENTIALS_ID = "aws-credentials"
---
> SECRET_AWS_CREDENTIALS_ID = "aws-credentials"

```
